---
title: "Project"
author: ''
date: '2022-10-27'
slug: project
categories: []
tags: []
---

## Project

- Guidelines: the goal of this project is to allow you make a connection
between course topics and real world. The course project is to push you get immersed in real life and is very important for us.

- Topics I suggested are as follows:

- 1. We talked about [China’s Foreign Trade: Perspectives From the Past 150 Years](https://chinawto.netlify.app/pdf/ChinaTrade150ys_Keller_Li_Shiue.pdf); based on the paper and other information you could get, replicate a paper [The United States in a New Global Economy? A Century's Perspective](https://chinawto.netlify.app/pdf/USinaNewGlobalEconomy.pdf) for a China's version.

- 2. The impart of [Belt and Road Initiative](https://en.wikipedia.org/wiki/Belt_and_Road_Initiative) on the world trade and the trade of China. In the west, it is considered as [Marshall Plan](https://en.wikipedia.org/wiki/Marshall_Plan).

- 3. The impact of Russia Ukraine war on the world trade and the trade of China. 
- 4. You can pick your own topic, as long as it is related to the course content.


- The project is worth $100$ points.

## Due Dates: 
   - the proposal due by **5pm Monday, Nov. 7**;
   - the slides due by **5pm Monday, Nov. 14**;
   - the presentation at **1:30 p.m. - 2:45 p.m. Thursday, Nov.17**;
   - the final writeup due by **5pm Monday, Nov. 21**.
   
## Grades: 

   - the proposal: $20$;
   - the slides: $30$;
   - The presentation: $25$;
   - the final writeup: $25$.